=== businessman64/AutoWestCOMMENTS/out/production/AutoWest/data/RailwayData/overviews.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 rel. 2 (http://www.altova.com) by Steven Baker (private) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="common-types.xsd"/>
	<xs:element name="Railway">
		<xs:annotation>
			<xs:documentation>Overviews used for overview displays. Groups many objects into one</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="OverviewObjectsType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="OverviewTracksType">
		<xs:sequence>
			<xs:element name="OverviewTrack" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="track" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>All tracks used to drive the overview track.</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:attribute name="id" type="railwayObjectId" use="required">
									<xs:annotation>
										<xs:documentation>id of an existing track.</xs:documentation>
									</xs:annotation>
								</xs:attribute>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="id" use="required">
						<xs:annotation>
							<xs:documentation>Unique id of the overview track.</xs:documentation>
						</xs:annotation>
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:minLength value="1"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
				<xs:unique name="track_ids">
					<xs:selector xpath=".//track"/>
					<xs:field xpath="@id"/>
				</xs:unique>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="OverviewBerthsType">
		<xs:sequence>
			<xs:element name="OverviewBerth" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="berth" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>All berths used to drive the overview berth.</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:attribute name="id" type="railwayObjectId" use="required">
									<xs:annotation>
										<xs:documentation>id of an existing berth</xs:documentation>
									</xs:annotation>
								</xs:attribute>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="id" use="required">
						<xs:annotation>
							<xs:documentation>Unique id of the overview berth.</xs:documentation>
						</xs:annotation>
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:minLength value="1"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
				<xs:unique name="berth_ids">
					<xs:selector xpath=".//berth"/>
					<xs:field xpath="@id"/>
				</xs:unique>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="OverviewObjectsType">
		<xs:sequence>
			<xs:element name="Header" type="HeaderType"/>
			<xs:element name="OverviewBerths" type="OverviewBerthsType" minOccurs="0" maxOccurs="unbounded">
				<xs:unique name="ob_ids">
					<xs:selector xpath=".//OverviewBerth"/>
					<xs:field xpath="@id"/>
				</xs:unique>
			</xs:element>
			<xs:element name="OverviewTracks" type="OverviewTracksType" minOccurs="0" maxOccurs="unbounded">
				<xs:unique name="ot_ids">
					<xs:selector xpath=".//OverviewTrack"/>
					<xs:field xpath="@id"/>
				</xs:unique>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== businessman64/AutoWestCOMMENTS/out/production/AutoWest/data/RailwayData/RailwayOverviews.xml
<?xml version="1.0" encoding="UTF-8"?>
<Railway xsi:noNamespaceSchemaLocation="overviews.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Header version="Mernda" date="02/05/2018" source="Core TCMS - HMI Overview Object Register.xlsx"/>
	<OverviewBerths>
		<OverviewBerth id="OV3/B5301">
			<berth id="FKS/BT512"/>
			<berth id="NMU/BT510"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV3/B5302">
			<berth id="NMU/BT473"/>
			<berth id="FKS/BT475"/>
			<berth id="FKS/BT539"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV3/B5303">
			<berth id="NMU/BT553"/>
			<berth id="FKS/BT483"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV3/B5304">
			<berth id="FKS/BT482"/>
			<berth id="NMU/BT450"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV3/B5305">
			<berth id="SSN/BT561"/>
			<berth id="SSN/BT465"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV3/B5306">
			<berth id="SSN/BT930"/>
			<berth id="SSN/BT928"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV3/B5307">
			<berth id="NMU/BT400"/>
			<berth id="MUL/BT403"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV3/B7108">
			<berth id="NME/BT788"/>
			<berth id="FKS/BT900"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV3/B7109">
			<berth id="TSS/BT806"/>
			<berth id="TSS/BT716"/>
			<berth id="TSS/BT842"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV3/B7111">
			<berth id="TSS/BT816"/>
			<berth id="TSS/BT621X"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV3/B7113">
			<berth id="TSS/BT819"/>
			<berth id="FSA/BT923"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV3/B7114">
			<berth id="MUL/BT604"/>
			<berth id="MUL/BT602"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV3/B3115">
			<berth id="MUL/BT202"/>
			<berth id="MUL/BT204"/>
			<berth id="MUL/BT210"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV3/B1116">
			<berth id="MUL/BT189"/>
			<berth id="MUL/BT006"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV3/B5217">
			<berth id="MUL/BT425"/>
			<berth id="MUL/BT472"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV3/B7118">
			<berth id="FKS/BP611D"/>
			<berth id="FKS/BT805"/>
			<berth id="FKS/BT803"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV3/B1119">
			<berth id="SSS/BT083"/>
			<berth id="SSN/BT126"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV3/B3120">
			<berth id="SSS/BT283"/>
			<berth id="SSN/BT304"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV3/B5221">
			<berth id="SSS/BT491"/>
			<berth id="SSN/BT492"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV3/B5222">
			<berth id="SSS/BT705"/>
			<berth id="SSN/BT680"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV3/B5323">
			<berth id="SST/BT562"/>
			<berth id="SST/BP432"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV4/B7101">
			<berth id="MUL/BT615"/>
			<berth id="MUL/BT617"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV4/B3102">
			<berth id="MUL/BT388"/>
			<berth id="MUL/BT213"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV4/B5203">
			<berth id="MUL/BT588"/>
			<berth id="MUL/BT415"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV4/B7204">
			<berth id="MUL/BT620"/>
			<berth id="MUL/BT791"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV4/B5205">
			<berth id="MUL/BT424"/>
			<berth id="MUL/BT432"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV4/B1206">
			<berth id="MUL/BT024"/>
			<berth id="MUL/BT191"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV4/B7207">
			<berth id="MUL/BT790"/>
			<berth id="MUL/BT635"/>
			<berth id="MUL/BT629"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV4/B3208">
			<berth id="MUL/BT237"/>
			<berth id="MUL/BT390"/>
			<berth id="MUL/BT229"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV4/B1209">
			<berth id="MUL/BT041"/>
			<berth id="MUL/BT039"/>
			<berth id="MUL/BT190"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV4/B7210">
			<berth id="MUL/BT644"/>
			<berth id="MUL/BT646"/>
			<berth id="MUL/BT650"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV4/B3211">
			<berth id="MUL/BT393"/>
			<berth id="MUL/BT250"/>
			<berth id="MUL/BT254"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV4/B5112">
			<berth id="MUL/BT437"/>
			<berth id="MUL/BT499"/>
			<berth id="MUL/BT452"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV4/B1213">
			<berth id="MUL/BT193"/>
			<berth id="MUL/BT046"/>
			<berth id="MUL/BT052"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV4/B1114">
			<berth id="SSS/BT084"/>
			<berth id="SSS/BT086"/>
			<berth id="FSA/BT148"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV4/B3115">
			<berth id="SSS/BT284"/>
			<berth id="SSS/BT286"/>
			<berth id="FSA/BT328"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV4/B5216">
			<berth id="FSA/BT498"/>
			<berth id="SSS/BT496"/>
			<berth id="SSS/BT494"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV4/B7217">
			<berth id="SSS/BT684"/>
			<berth id="SSS/BT686"/>
			<berth id="FSA/BT688"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV4/B7118">
			<berth id="FSA/BT830"/>
			<berth id="TSS/BT838"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV4/B7219">
			<berth id="FSA/BP644U"/>
			<berth id="FSA/BT925"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV4/B1120">
			<berth id="SSS/BT127"/>
			<berth id="FSA/BT085"/>
			<berth id="FSA/BT087"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV4/B3121">
			<berth id="SSS/BT307"/>
			<berth id="FSA/BT285"/>
			<berth id="FSA/BT287"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV4/B5222">
			<berth id="FSA/BT495"/>
			<berth id="FSA/BT497"/>
			<berth id="SSS/BT569"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV4/B7223">
			<berth id="SSS/BT709"/>
			<berth id="FSA/BT685"/>
			<berth id="FSA/BT687"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV4/B0424">
			<berth id="FSB/BT945"/>
			<berth id="FSB/BTDT945"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV4/B7225">
			<berth id="FSB/BT964"/>
			<berth id="FSB/BTDT964"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV4/B1226">
			<berth id="FSD/BT157"/>
			<berth id="FSD/BTDT157"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV5/B3301">
			<berth id="MUL/BT266"/>
			<berth id="MUL/BT259"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV5/B5101">
			<berth id="MUL/BT470"/>
			<berth id="FSD/BT463"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV5/B1201">
			<berth id="MUL/BT161"/>
			<berth id="MUL/BT192"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV5/B7401">
			<berth id="FSE/BT670"/>
			<berth id="FSE/BT760"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV5/B7301">
			<berth id="FSE/BT659"/>
			<berth id="FSE/BT657"/>
			<berth id="MUL/BT655"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV5/B1202">
			<berth id="JLI/BT099"/>
			<berth id="JLI/BT185"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV5/B3302">
			<berth id="FSE/BT372"/>
			<berth id="FSE/BT358"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV5/B7302">
			<berth id="FSE/BT770"/>
			<berth id="FSB/BT764"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV5/B7402">
			<berth id="FSE/BT676"/>
			<berth id="FSE/BT674"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV5/B3303">
			<berth id="FSE/BT375"/>
			<berth id="FSE/BT276"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV5/B7303">
			<berth id="FSE/BT700"/>
			<berth id="FSB/BT696"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV5/B7403">
			<berth id="SYR/BTB069"/>
			<berth id="FSE/BT869"/>
			<berth id="FSE/BT888"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV5/B3304">
			<berth id="FSE/BT396"/>
			<berth id="FSE/BT296"/>
			<berth id="FSE/BT241"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV5/B7304">
			<berth id="FSB/BT850"/>
			<berth id="FSB/BT852"/>
			<berth id="FSE/BT856IB"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV5/B3305">
			<berth id="FSE/BT275"/>
			<berth id="FSE/BT277"/>
			<berth id="FSE/BT280"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV5/B7305">
			<berth id="FSE/BT870"/>
			<berth id="FSE/BT981"/>
		</OverviewBerth>
	</OverviewBerths>
	<OverviewBerths>
		<OverviewBerth id="OV5/B3306">
			<berth id="FSE/BT216"/>
